# Generated by Django 5.2.3 on 2025-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_student_age_student_email_student_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
