# Generated by Django 5.2.3 on 2025-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='chapter_count',
            field=models.IntegerField(),
        ),
    ]
